### ISSUE TITLE
How to authenticate SteamCMD?

### ISSUE THREAD

**Issue by ben-yarwood** [ohmcodes/WindowsGSM.Enshrouded#2]
Apologies, I know this isn't strictly related to Enshrouded, but I'm wondering how to authenticate steamcmd to allow the installation to complete?

Currently have "ERROR! Failed to install app '2278520' (No subscription)"

**Comment by Boolty** [comment]
use the app id = 2612550
but the server files are damaged

**Comment by ben-yarwood** [comment]
> use the app id = 2612550 but the server files are damaged

That appears to be for "The Front" ? https://steamdb.info/app/2612550/info/

**Comment by Boolty** [comment]
> > use the app id = 2612550 but the server files are damaged
> 
> That appears to be for "The Front" ? https://steamdb.info/app/2612550/info/

my bad this it is from mmo-forum.de

**Comment by ohmcodes** [comment]
download latest release and please dont follow that site showing the Front guide
