### ISSUE TITLE
Exit Code:8 during game server install

### ISSUE THREAD

**Issue by quotabat** [ohmcodes/WindowsGSM.Enshrouded#3]
Getting Error Exit Code 8 when trying to install game server using windows gsm

![image](https://github.com/ohmcodes/WindowsGSM.Enshrouded/assets/118788463/4085f898-1aab-4bdf-bef6-f1b2802f2ddb)

**Comment by Boolty** [comment]
Use the appid 2612550

**Comment by quotabat** [comment]
@Boolty How do I do that? I don't see an area to change the app id for the install

**Comment by quotabat** [comment]
I was able to change the app ID in the .cs file but now I am getting this error code, 
![image](https://github.com/ohmcodes/WindowsGSM.Enshrouded/assets/118788463/652b8e5b-28b8-44f4-a5cd-5733b3ec3616)

**Comment by PetitCastor** [comment]
Server files seems damaged

**Comment by Boolty** [comment]
open the zip file WindowsGSM.Enshrouded-main.zip\WindowsGSM.Enshrouded-main\Enshrouded.cs
Change the 
from
public override string AppId => "2278520"; // Game server appId Steam
to
public override string AppId => "2612550"; // Game server appId Steam
but the server files are damaged

**Comment by Boolty** [comment]
> Server files seems damaged

yes, but Enshrouded has to fix that

**Comment by quotabat** [comment]
ahhhh.. so does this mean there is no way to host a dedi server for the game right now until they fix it im guessing?

**Comment by Boolty** [comment]
> ahhhh.. so does this mean there is no way to host a dedi server for the game right now until they fix it im guessing?

I think at least I haven't found a way. If I fix the first error, the next one will come.

The first error is an incorrectly named file from the server

**Comment by Boolty** [comment]
i Found this 
2278520 | Tool | Enshrouded Dedicated Server |   | 19 minutes ago

Mybe the download is Locked

**Comment by quotabat** [comment]
Yup that is the correct app id, found this is their discord, 
Community Tools & Self Hosting Resources
a list of community resources for hosting enshrouded servers

Docker Containers, Pterodactyl Eggs, AMP, WindowsGSM Install Guides: https://github.com/PR3SIDENT/enshrouded-server
Hosting Providers (Community Sourced List): https://github.com/PR3SIDENT/enshrouded-server/blob/main/Hosting%20Providers/hosting-providers.md (if you would like to be added to this list please submit a PR)
The SteamCMD is not live yet, nothing will work until this is published. Not even hosting providers.... The Keen Games team is working on it.

**Comment by quotabat** [comment]
https://steamdb.info/app/2278520/history/

**Comment by ohmcodes** [comment]
download latest release
