### ISSUE TITLE
Replace .json when started

### ISSUE THREAD

**Issue by fantomgr** [ohmcodes/WindowsGSM.Enshrouded#6]
i add the plugin and the game at windows gsm,  then i go to .json file to fix my settings. All is fine until now .... Then i press start and i checked ingame the server but not take any setting and return to default. When i go back to .json file i see all the setting at default. I close the windows gsm and i start the game manual with the settings again fixed and work perfect. I check the windows gsm and run the game from there and again default setting .....

**Comment by ohmcodes** [comment]
> i add the plugin and the game at windows gsm, then i go to .json file to fix my settings. All is fine until now .... Then i press start and i checked ingame the server but not take any setting and return to default. When i go back to .json file i see all the setting at default. I close the windows gsm and i start the game manual with the settings again fixed and work perfect. I check the windows gsm and run the game from there and again default setting .....

please download latest version
