### ISSUE TITLE
Config.json format mismatch 

### ISSUE THREAD

**Issue by SlyNingen** [ohmcodes/WindowsGSM.Enshrouded#9]
The way that the current .cs outputs the format for the config.json of enshrouded is as follows for the ports and slots.

  "gamePort": "15636",
  "queryPort": "15637",
  "slotCount": "10"

But in order for it to actually take the values into account if you modify them they have to be unquoted. 

such as this:

  "gamePort": 15646,
  "queryPort": 15647,
  "slotCount": 12
  
  I had found that out by googling and testing it, just in case anyone else has an issue.

**Comment by ohmcodes** [comment]
updated
